### ISSUE TITLE
html output handling of < and > prevents copy and paste

### ISSUE THREAD

**Issue by zapashcanon** [Lelio-Brun/Obelisk#12]
Hi,

The way `<` and `>` are handled in the generated HTML is a little bit... unusual. Using `&lt;` and `&gt;` would be better. What do you think ? This one is easy, so I'll make a PR.

**Comment by Lelio-Brun** [comment]
Oh yes I have troubles remembering the rationale behind this but I think I wanted users to be able to change the delimiters easily, so I thought it would be better to have theme handled by CSS...
I didn't know it would prevent copy-pasting though... (but it seems obvious now that I think about it, if it is style then it is not content so it shouldn't be copy-able)

**Comment by Lelio-Brun** [comment]
Hi, I finally merged your PR, thanks a lot! 
I add options (`-css` and `-nocss`) to switch between the former HTML printer and yours, and I updated the README to give a brief explanation. 

The new version is currently submitted to opam and should be available soon.
