### ISSUE TITLE
Output EBNF for railroad diagram

### ISSUE THREAD

**Issue by mingodad** [Lelio-Brun/Obelisk#14]
Would be nice if this tool could output an EBNF accepted by https://www.bottlecaps.de/rr/ui .

Ideally menhir would have an option to output this kind of naked grammar to facilitate the work like I did for bison, byacc, ... here https://github.com/mingodad/lalr-parser-test .

See discussion here https://github.com/stan-dev/stanc3/issues/1142 .

**Comment by Lelio-Brun** [comment]
I add support for EBNF in `dev` branch, could you try it and tell me if it's okay for what you had in mind? 
I checked with Obelisk's parser that it works with the railroad diagram generator you mentioned but maybe I missed some corner cases.
