### ISSUE TITLE
[LaTeX] Add an option to generate only the grammar

### ISSUE THREAD

**Issue by grayswandyr** [Lelio-Brun/Obelisk#2]
Unless I'm mistaken, it's only possible to generate a complete, standalone file, as of now. If so, it would be nice to add an option to generate only the grammar part, in order to include it in a larger document.

**Comment by Lelio-Brun** [comment]
Well indeed I thought about it, but the problem is that additional packages and command definitions are needed.
I may add an option to produce 2 files:
1. the grammar part itself to be included
2. a _.sty_ file gathering extra `\RequirePackage` and `\newcommand` statements as a package to be required 

What about this solution ?

**Comment by grayswandyr** [comment]
I think it's OK. However, to avoid name clashes with other commands and even with many Obelisk grammars inserted at the same time, I think it would be good to prefix every command name with a (configurable?) string (and the style file should itself come with a configurable name).

**Comment by Lelio-Brun** [comment]
Ok, that is a good idea, I will work on it.

**Comment by Lelio-Brun** [comment]
Let me now if you think it's ok, the new version is available on the master branch. 
You can easily build Obelisk manually from there and do some tests, then I will publish an updated release on OPAM if everything is fine.

**Comment by grayswandyr** [comment]
Thanks. There is a problem if I include two grammars in the same file as both `sty` files define the `grammar` environment (as well as a bunch of commands that are not prefixed either). Is it the expected behavior? If not, I think the best solution is to prefix these names too.

**Comment by Lelio-Brun** [comment]
Thanks for the feedback! 

My bad, I thought that the overwriting would be silent and not harmful since it would be strange to use different submodes (tabular, syntaxes, backnaur) in a same document. 

Errors yield because I use `\newcommand` and not `\let`. 

I will add the prefix to structural commands too.

**Comment by Lelio-Brun** [comment]
Should be OK now (let's hope :sweat_smile:).
You can give it another try in the master branch.

**Comment by Lelio-Brun** [comment]
Actually I forgot to commit one file, so it didn't build.
Now it is OK.

**Comment by grayswandyr** [comment]
I think it's OK. Thanks.

Three more questions though (I'll let you see whether you'd like to make new issues out of them):
- Why don't you generate macros for non-terminals too, along those for terminals?
- When you define such macros, why don't you define them using the macros for terminals and non-terminals, e.g. `\newcommand\eleAND{\elegramterm{AND}}` (instead of `\newcommand\eleAND{AND}` and then `\elegramterm{\eleAND{}}` at call site, as is currently done)? It seems to me it gives more control to the user. 
- It would be nice to use the `longtabu` environment instead of `tabu`, to allow nice page breaks. The documentation says it doesn't mix well with math, but it seems to be OK with a basic Menhir grammar at least (even when showing some terminals as LaTeX mathematical symbols).

**Comment by Lelio-Brun** [comment]
Nice !
A v0.2.0 release should be available in OPAM soon.

> Why don't you generate macros for non-terminals too, along those for terminals?

Actually I just didn't think about it but it seems like a good idea.

> When you define such macros, why don't you define them using the macros for terminals and non-terminals

Yes indeed. Actually I was considering macros as a way to redefine merely the names of the tokens, but you are right about the control.

> It would be nice to use the longtabu environment instead of tabu, to allow nice page breaks.

I will investigate on this.

Thanks again for the feedback !
