### ISSUE TITLE
[LaTeX] Incorrect or dubious printing

### ISSUE THREAD

**Issue by grayswandyr** [Lelio-Brun/Obelisk#3]
The following file does not produce a very nice output for `comma_sep` and `comma_sep1`:
```
%public %inline comma_sep(X) :
  xs = separated_list(COMMA, X)
    { xs }

%public %inline comma_sep1(X) :
  xs = separated_nonempty_list(COMMA, X)
    { xs }
```

**Comment by Lelio-Brun** [comment]
What options do you use? with `obelisk latex` I obtain:

![test](https://user-images.githubusercontent.com/20226144/27957364-7817dcd8-631e-11e7-9577-33eb40ab6a55.png)

In the LaTeX file, you can control the way `separated_list` and `separated_nonempty_list` are printed by rewriting the body of the following commands (the first argument being the separator):
```latex
\newcommand\bnfseplist[2]{#2\ensuremath{_{\textnormal{#1}}^*}}
\newcommand\bnfsepnelist[2]{#2\ensuremath{_{\textnormal{#1}}^+}}
```

**Comment by grayswandyr** [comment]
Oops yes, thanks, I will just rewrite these commands.
