### ISSUE TITLE
Productions starting with "end" generate wrong Latex

### ISSUE THREAD

**Issue by haskellcamargo** [Lelio-Brun/Obelisk#7]
Consider the following production definition:

```ocaml
endif: END | ENDIF { }
```
In Latex version, it will generate a `\newcommand\endif{end\_if}`, however, `\newcommand` definitions are not allowed to have names starting with `end`, or it will emit an error. The generated code for productions starting with `end` should be with `\def` instead.

**Comment by haskellcamargo** [comment]
Having a deterministic generation system (sequentially deterministic) could be better than random, but, instead of generating 3 random characters, maybe prefixing them with something like `zzz` or anything less usual could cause less clashes than randomly defining them, because random definitions still can conflict with other ones (randomly or predefined ones), but conflicts become predictable with some prefix. The better way, I think, is to prefix not only the `end_` ones, but all the productions, so we can avoid name clashing. The good part is that also productions starting with the common prefix are prefixed again, so, no worries.

**Comment by Lelio-Brun** [comment]
Yes I see your point.
In fact what you ask for already exists with the `-prefix <myprefix>` option but for the sake of soundness I will get rid of the non-determinism adding "zzz" as a prefix for `end`-beginning commands as you suggest, mentioning it in the README.
