### ISSUE TITLE
Display of pairs seems erroneous

### ISSUE THREAD

**Issue by marctrem** [Lelio-Brun/Obelisk#8]
The grammar
```
edn_assoc:
  | BEGIN_ASSOC; lp = list(pair(value, value)); RIGHT_BRACE { lp }
;
```
will result in
```
<edn_assoc> ::= BEGIN_ASSOC <value> <value>* RIGHT_BRACE
```
and I would expect
```
<edn_assoc> ::= BEGIN_ASSOC (<value> <value>)* RIGHT_BRACE
```

Please let me know if there something I'm missing!
Also, thank you for the great software :+1:

**Comment by Lelio-Brun** [comment]
You are not missing anything, this is a bug indeed.
This is related to the way parentheses are used or not, and this is erroneous, obviously.
I will investigate it as soon as I can.

Thank you very much for reporting!

**Comment by Lelio-Brun** [comment]
This is now fixed in the master branch, and an update should be available soon in OPAM.
Thanks again!
