### ISSUE TITLE
support the new syntax ?

### ISSUE THREAD

**Issue by zapashcanon** [Lelio-Brun/Obelisk#9]
Hi,

There's a [new syntax](http://gallium.inria.fr/~fpottier/menhir/manual.pdf#subsection.4.3) available in menhir. In practice, it looks [like this](https://git.zapashcanon.fr/zapashcanon/dddddml/src/branch/master/src/parser.mly). I'm wondering if you have any plan to add support for this new syntax in obelisk ?

Cheers,

**Comment by Lelio-Brun** [comment]
Hi!
 
I have been aware of the new syntax and willing to support it for a while now, but I have been busy writing my thesis. 
I guess I will have more time to work on it now...

**Comment by Lelio-Brun** [comment]
Hi, finally the new syntax is supported, and the OPAM update has been submitted. 
Thanks again!

**Comment by zapashcanon** [comment]
Hi ! I just tried it and it works. Thanks !
